### ISSUE TITLE
fastfloat vs fast_float?

### ISSUE THREAD

**Issue by biojppm** [fastfloat/fast_float#43]
Can either of the organization/repo names be changed to the other? The current situation is misleading; I was already bitten by the difference while cloning, and I'm sure many more people will also have this.

**Comment by lemire** [comment]
The name of the org could not have an underscore in it.

Changing the name of the repo might break links but it is doable.

**Comment by biojppm** [comment]
Now would be the time to do it. If we're going to bother people with the change, let's do it all at once. :-)

**Comment by biojppm** [comment]
Oh, just remembered the header names also have the underscore. That maybe balances things to the current situation. Or maybe not. Your call.

**Comment by lemire** [comment]
It is a bit tricky. 

I am not against the change but we should not make things worse.

**Comment by lemire** [comment]
The library implements "from_chars" so it is more logical to call it "fast_float" than "fastfloat".

The organisation name is distinct. An organisation can carry several distinct projects. So the organization (fastfloat) could be host of several different projects, not just fast_float (the library). There is thus no reason that the names be the same. I would have preferred the org name to match, but it is not possible (error: "Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen"). It did not match before (it was lemire). It does not match now (fastfloat).

This library is already in use at this point (in Apache Arrow among others) so changing the name, the namespace and so forth would have a non-trivial cost. Moving from my personal repository to an org repository is painless because GitHub does the redirection. If we change the library name, we definitively do not get a seamless redirection: it breaks links.

The benefits seem slim. They seem to concern folks who assume that the library name and the org name must be the same.


I would expect most people who clone this repository to just do

```
git clone git@github.com:fastfloat/fast_float.git
```

copying and pasting from the repo name from the web or some documentation. 

I would not expect users to type this address out of memory. But even if one does... the error would be "fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists." So then one would probably double check the path and realize the error.

What could have been done is to use a drastically different org name. We could still rename the org. But it is not obvious to me which name would be better. Again, it cannot be fast_float.


I agree that the setup is not ideal, as I would have liked it to be, but every fix I can think of would make things worse.


I would also prefer to avoid bike shedding issues in general.

**Comment by biojppm** [comment]
Fully agree.
