### ISSUE TITLE
Port to Java

### ISSUE THREAD

**Issue by lemire** [fastfloat/fast_float#58]
We need a port to Java.

I think that @elbosso has offered their help. I am willing to work on it.

A C# port is almost ready to be made public.

**Comment by elbosso** [comment]
few remarks first:
* thankfully, there are (official) tests for parsing Doubles in Openjdk - namely https://searchcode.com/codesearch/view/17998396/
* in OpenJDK the Class Double does not really offer an implementation of the method `parseDouble` - it instead delegates to `VMDouble`
* it is very probable `VMDouble` is implemented in pure C - meaning it will be harder to outperform this code with a new implementation
* first,  it is necessary to make a rather crude benchmark for ascertaining the time it takes to parse double numbers using the traditional approach
  * that means to measure the time it takes to produce random double numbers as Strings
  * so that this time can then be subtracted from the time it takes to create a random double number as string and paarsing it back.

**Comment by lemire** [comment]
@elbosso Interesting.

In C#, the number parsing routines are written in C#. @CarlVerret had good luck porting fast float to C# and we are getting good results.

In Java, I am aware that there can be intrinsics, but at a glance, parseDouble goes to FloatingDecimal.java. You end up with `readJavaFormatString(s).doubleValue()`. The intermediate type/interface  is an ASCIIToBinaryConverter. At a glance, the implementation looks like the C# one, with the conventional Clinger's fast path followed by slower fallback. Given that we were able to accelerate the C# version, I am hopeful that we can accelerate this particular Java code.

Here is the link...

https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/jdk/internal/math/FloatingDecimal.java

It is entirely possible that this Java code is just a fall back for when no native (C) version is available... if so, we should be able to trace it back.

**Comment by elbosso** [comment]
OK - added the Clinger Optimization - Benchmarks look ok to me so far - the Code is a little faster than the one Java ships with (although that might be because of me not paying proper attention to all edge cases):

00:00:00.303040
00:00:00.220266
00:00:00.235971

Testdata: random 64 Bit BigInteger scaled randomly with 10^x where x is between -16 and 16

Explanation: first row: the system still settles down: Jit did not step in: second row: my Implementation so far; third row: java.,lang.Double.parseDouble. Each row is 1000000 times parsing of randomly (see above) generated Number Strings.

Now for the new methods.

**Comment by lemire** [comment]
@elbosso Looking forward to reading your code.

**Comment by elbosso** [comment]
Hmm - i am kind of stuck now. From what i read - the example i gave above should be well inside the margins to use the clinger approach - but when i do so - i get an inexact result.

To be clear: i compute 3974408480416.0*1.0E-8

I tried this in C also and it yields the same difference. I cannot help but suspect that there is a fundamental misunderstanding here. Will read up on it some more and try again tomorrow...

**Comment by lemire** [comment]
@elbosso I expect Java to already use Clinger's fast path. No?

**Comment by elbosso** [comment]
Yes, it does. It was entirely my fault - I did not read the paper as thorough as I should have: I skipped the part where it says: *we multiply (when q≥0) or divide(q<0)* , precomputed 10^-22  ... 10^22 and multiplied - that led to the error i mentioned. Now the parser is complete and still a little faster (around 5%) than the one java ships with. In a rather rough test i encountered no errors when i restrict the input to values so that Clingers approach is applicable. Now i *really* can get to the interesting part...

I append the current version of the code here (zipped because Github does not allow java sources
 directly as attachments). If you think that this could be used we could maybe think of a better way to do it- either as merge requests here or a separate project...

During the time i chased the bug i thought about the second-to-next steps: In Java, one can parse numbers using `Double.parseDouble` - this does not take locale or special formats into account : it follows a rather simple grammar (https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#valueOf(java.lang.String)). But it is also possible to parse numbers using `java.text.NumberFormat` (https://docs.oracle.com/javase/7/docs/api/java/text/NumberFormat.html) that does this. To exchange the former is easy: you just call your own Method instead of `Double.parseDouble`. The latter is (as I see it at the moment) trickier. I assume in C# it is the same - or at least comparable. How do you go about it there? Do you support locale-dependent parsing?

[FastFloat.java.zip](https://github.com/fastfloat/fast_float/files/6018031/FastFloat.java.zip)

**Comment by lemire** [comment]
> Do you support locale-dependent parsing?

The motivation for going faster has to do with scenarios where you exchange lots of serialized floats (JSON, CSV, and so forth). Though it is certainly possible to serialize floats in a locale-dependent manner, it is not commonly done in my experience.

**Comment by elbosso** [comment]
Hmm, after twiddling around a bit i doubt that this can be implemented in Java at all. 

There are a good many unsigned 64Bit operations in the algorithm and I have not yet found a sane way to do them in Java - the only simple possibilities are using BigInteger - but that comes with so much overhead that it will eat up all benefits. The datatype Long offers operations to treat a long as unsigned - but only with a select few - namely multiply is missing there. One could implement workarounds but again - I think that would eat up all the benefit. There are certain libraries offering unsigned 64bit types (for example UnsignedLong in Guava) but again - this being heavyweight class-types using them will eat up the performance gained by the algorithm. 

Currently I am pondering 
* to try using the c-implementation using jni and/or 
* implementing a "LongLong" type (128Bit) myself along the lines of https://github.com/ChiralBehaviors/Utils/blob/master/src/main/java/com/hellblazer/utils/math/DoubleDouble.java although i fear that the same argument can be made against it re: performance. Still - at the moment it seems (for me) an interesting enough challenge to try it...

**Comment by elbosso** [comment]
Well - as expected: the naive approach to put a call through JNI to parse a single value is ridiculously slow - even compared to standard java. However: it is impressive to see the speedup compared to the c(++) implementation...

**Comment by lemire** [comment]
> There are a good many unsigned 64Bit operations in the algorithm and I have not yet found a sane way to do them in Java

The only one that should be missing is the full product, which I do not think Java supports as an intrinsic (though it is a recent addition in C# too). Other than that, all operations should be supported. 

To simplify, can you pick one operation which you believe cannot be done efficiently in Java (ie without using BigInteger) ?

**Comment by lemire** [comment]
C# version: https://lemire.me/blog/2021/02/22/parsing-floating-point-numbers-really-fast-in-c/

Code: https://github.com/CarlVerret/csFastFloat

I expect that everything that can be done in C# should be doable in Java as well. Yes, I am aware that Java lacks unsigned integers, but I have never encountered a scenario where it was a real limitation. There are always workarounds... :-)

**Comment by elbosso** [comment]
I will try and be inspired by the c# port on the weekend - it must be possible...

**Comment by lemire** [comment]
I am sure it must be. The results are pretty good with C# and, historically, Java has been faster than C#... so...

**Comment by wrandelshofer** [comment]
I made a straightforward port from C++ to Java of your fast_double_parser. 
Its roughly 5.5 times faster than Double.parseDouble(). This is awesome! 

Porting was very easy, because the C++ code provides functions for the multiplication of unsigned 64 bit longs. @elbosso maybe this code might help you to port the code from this fast_float project to Java.

The code is here:
https://github.com/wrandelshofer/FastDoubleParser

**Comment by lemire** [comment]
@wrandelshofer Fantastic. Before closing this issue I'd like to be able to run your benchmarks. Can you provide instructions?

**Comment by wrandelshofer** [comment]
Here is how to download and run the benchmarks on macOS. You need Java 11 or above and the XCode command-line tools.

```
 git clone https://github.com/wrandelshofer/FastDoubleParser.git
 cd FastDoubleParser 
 javac -d out -encoding utf8 -sourcepath src/main/java test/main/java/ch/randelshofer/fastdoubleparser/FastDoubleParserBenchmark.java 
 java -classpath out ch.randelshofer.fastdoubleparser.FastDoubleParserBenchmark 
 java -classpath out ch.randelshofer.fastdoubleparser.FastDoubleParserBenchmark data/canada.txt
```

The output that you get should be similar to this:

```
Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
OpenJDK 64-Bit Server VM, Oracle Corporation, 16+36-2231

parsing random numbers in the range [0,1)
=== warmup 1000 times =====
=== number of trials 32 =====
FastDoubleParser               MB/s avg: 345.948764, min: 293.84, max: 362.76
FastDoubleParserFromByteArray  MB/s avg: 517.933032, min: 467.59, max: 560.61
Double                         MB/s avg: 87.660476, min: 75.49, max: 91.82
Speedup FastDoubleParser              vs Double: 3.946462
Speedup FastDoubleParserFromByteArray vs Double: 5.908399


You can also provide a filename: it should contain one string per line corresponding to a number.
Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
OpenJDK 64-Bit Server VM, Oracle Corporation, 16+36-2231

parsing numbers in file /Users/wr/Desktop/test/FastDoubleParser/data/canada.txt
read 111126 lines
=== warmup 1000 times =====
=== number of trials 32 =====
FastDoubleParser               MB/s avg: 341.802887, min: 294.67, max: 373.40
FastDoubleParserFromByteArray  MB/s avg: 442.440788, min: 399.96, max: 472.12
Double                         MB/s avg: 83.539265, min: 70.14, max: 89.27
Speedup FastDoubleParser              vs Double: 4.091524
Speedup FastDoubleParserFromByteArray vs Double: 5.296202
```

The output shows, that we can achieve approximately up to 4 times speedup from java.lang.Double with our FastDoubleParser class.

It is even possible to achieve up to 6 times speedup with FastDoubleParserFromByteArray. However FastDoubleParserFromByteArray needs a byte array as input, so that it can parse up to 8 digits at once, like the code in fast_float does.

**Comment by lemire** [comment]
Thanks for the report. Closing.
